{
 "title": "AWS-Mock",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg_over_time(total_cpu[5m])", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(real_memory_used [5m])",
     "legendFormat": "Real Memory"
    },
    {
     "expr": "avg_over_time(virtual_memory_used [5m])",
     "legendFormat": "VIrtual Memory"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(total_threads[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(http_get_time[5m])",
     "legendFormat": "GET"
    },
    {
     "expr": "avg_over_time(http_put_time[5m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg_over_time(http_post_time[5m])",
     "legendFormat": "POST"
    },
    {
     "expr": "avg_over_time(http_delete_time[5m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "avg_over_time(http_options_time[5m])",
     "legendFormat": "OPTIONS"
    },
    {
     "expr": "avg_over_time(http_head_time[5m])",
     "legendFormat": "HEAD"
    }
   ]
  }
 ]
}