{
 "title": "S3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Buckets",
   "type": "timeseries",
   "description": "Total number of all buckets",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "s3_bucket_count_total", "legendFormat": "Buckets" }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "description": "Total number of objects",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "s3_object_count_total", "legendFormat": "Objects" }
   ]
  },
  {
   "title": "Objects per bucket",
   "type": "timeseries",
   "description": "Total number of objects",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(s3_bucket_count{}[5m])",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}