#!/bin/bash

#
# S3 function
#
function bucket_exists() {
  awsmock s3 ls | grep $1 | wc -l
}

function delete_s3_bucket(){
  if [ "$(bucket_exists "$1")" -gt 0 ]; then
    awsmock s3 rm "s3://$1" --recursive > /dev/null 2>&1
    awsmock s3 rb "s3://$1" > /dev/null 2>&1
    echo "Bucket $1 deleted"
  else
    echo "Bucket $1 does not exist"
  fi
}

#
# SQS function
#
function queue_exists() {
  awsmock sqs list-queues | grep $1 | wc -l
}

function delete_sqs_queue(){
  if [ "$(queue_exists "$1")" -gt 0 ]; then
    awsmock sqs delete-queue --queue-url "http://localhost:4567/000000000000/$1-queue" > /dev/null 2>&1
    awsmock sqs delete-queue --queue-url "http://localhost:4567/000000000000/$1-dlqueue" > /dev/null 2>&1
    echo "Queue $1 deleted"
  else
    echo "Queue $1 does not exist"
  fi
}

#
# SNS function
#
function topic_exists() {
  awsmock sns list-topics | grep $1 | wc -l
}

function delete_sns_topic(){
  if [ "$(topic_exists "$1")" -gt 0 ]; then
    awsmock sns delete-topic --topic-arn arn:aws:sns:eu-central-1:000000000000:$1 > /dev/null 2>&1
    echo "Topic $1 deleted"
  else
    echo "Topic $1 does not exist"
  fi
}

#
# Lambda function
#
function lambda_exists() {
  awsmock lambda list-functions | grep arn | grep $1 | wc -l
}

function delete_lambda_function(){
  if [ "$(lambda_exists "$1")" -gt 0 ]; then
    awsmock lambda delete-function --function-name "$1" > /dev/null 2>&1
    echo "Lambda $1 deleted"
  else
    echo "Lambda $1 does not exist"
  fi
}

#
 # Transfer server
 #
 function transfer_exists() {
   awsmock transfer list-servers | grep "Arn" | wc -l
 }

 function delete_transfer_server {
   if [ "$(transfer_exists)" -gt 0 ]; then
     SERVERID=$(awsmock transfer list-servers | jq -r '.Servers[].ServerId')
     awsmock transfer delete-server --server-id "$SERVERID" > /dev/null 2>&1
     echo "Transfer server $SERVERID deleted"
   else
     echo "Transfer server does not exist"
   fi
 }

#
# Main
#

#
# Delete S3 objects
#
delete_s3_bucket file-delivery
delete_s3_bucket file-delivery-origin
delete_s3_bucket json-parsing-results
delete_s3_bucket onix3-produktmeldungen
delete_s3_bucket transfer-server
delete_s3_bucket transformed-images
delete_s3_bucket inventory-reports
delete_s3_bucket onix3-tmp-parsing-input
delete_s3_bucket onix3-tmp-anreicherungs-input
delete_s3_bucket katalogdaten-export-bucket
delete_s3_bucket vlb-preisreferenz-parsing-input
delete_s3_bucket vlb-preisreferenz-parsing-result

#
# Delete SQS Queues
#
delete_sqs_queue file-logging
delete_sqs_queue protokollierung
delete_sqs_queue ftp-file-distribution-vlb-preisreferenz
delete_sqs_queue ftp-file-distribution-image
delete_sqs_queue ftp-file-distribution-onix
delete_sqs_queue ftp-file-distribution-inventory-feed
delete_sqs_queue image-input
delete_sqs_queue image-result
delete_sqs_queue vlb-preisreferenz-splitting-result
delete_sqs_queue parsing-result
delete_sqs_queue artikel-transformations-service-artikel-ausgang
delete_sqs_queue daten-lieferanten-service-daten-eingang
delete_sqs_queue daten-datenlieferanten-notification
delete_sqs_queue textannotation-result
delete_sqs_queue bilderlink
delete_sqs_queue produktmeldung-parsing
delete_sqs_queue image-delete-notification
delete_sqs_queue onix3-datenlieferant-updates
delete_sqs_queue protokollierung-datenlieferant-updates
delete_sqs_queue katalogdaten
delete_sqs_queue onix3-tmp-parsing-input-event
delete_sqs_queue onix3-tmp-anreicherungs-input-event
delete_sqs_queue inventory-feed-parsing-result

#
# Delete lambda function
#
delete_lambda_function ftp-file-copy
delete_lambda_function ftp-file-distribution
delete_lambda_function image-transformation
delete_lambda_function vlb-preisreferenz-splitting

#
# Delete SNS topic
#
delete_sns_topic protokollierung-topic
delete_sns_topic datenlieferant-updates

#
# Delete transfer server
#
delete_transfer_server