#!/bin/bash

#
# Delete S3 objects
#
awsmock s3 rm s3://file-delivery1 --recursive
awsmock s3 rm s3://file-delivery2 --recursive
awsmock s3 rm s3://file-delivery3 --recursive

#
# Delete S3 buckets
#
awsmock s3 rb s3://file-delivery1
awsmock s3 rb s3://file-delivery2
awsmock s3 rb s3://file-delivery3

#
# Delete SQS Queues
#
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-delivery1-queue
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-delivery1-dlqueue
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-delivery2-queue
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-delivery2-dlqueue
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-delivery3-queue
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-delivery3-dlqueue
awsmock sqs delete-queue --queue-url=http://localhost:4567/000000000000/file-logging-queue

#
# Delete lambda function
#
awsmock lambda delete-function --function-name ftp-file-copy

#
# Delete SNS topic
#
awsmock sns delete-topic --topic-arn arn:aws:sns:eu-central-1:000000000000:file-logging-topic
