#!/bin/bash

#
# S3 function
#
function delete_s3_bucket(){
  awsmock s3 rm "s3://$1" --recursive
  awsmock s3 rb "s3://$1"
}

#
# SQS function
#
function delete_sqs_queue(){
  awsmock sqs delete-queue --queue-url "http://localhost:4567/000000000000/$1-queue" > /dev/null
  awsmock sqs delete-queue --queue-url "http://localhost:4567/000000000000/$1-dlqueue" > /dev/null
  echo "Queue $1 deleted"
}

#
# SNS function
#
function delete_sns_topic(){
  awsmock sns delete-topic --topic-arn arn:aws:sns:eu-central-1:000000000000:$1
}

#
# Lambda function
#
function delete_lambda_function(){
  awsmock lambda delete-function --function-name "$1" > /dev/null
}

#
# Main
#

#
# Delete S3 objects
#
delete_s3_bucket file-delivery
delete_s3_bucket json-parsing-results
delete_s3_bucket onix3-produktmeldungen
delete_s3_bucket transfer-server
delete_s3_bucket transformed-images
delete_s3_bucket inventory-reports
delete_s3_bucket onix3-tmp-parsing-input
delete_s3_bucket onix3-tmp-anreicherungs-input
delete_s3_bucket katalogdaten-export-bucket
delete_s3_bucket vlb-preisreferenz-parsing-input
delete_s3_bucket vlb-preisreferenz-parsing-result

#
# Delete SQS Queues
#
delete_sqs_queue file-delivery
delete_sqs_queue file-logging
delete_sqs_queue protokollierung
delete_sqs_queue ftp-file-distribution-vlb-preisreferenz
delete_sqs_queue ftp-file-distribution-image
delete_sqs_queue ftp-file-distribution-onix
delete_sqs_queue ftp-file-distribution-inventory-feed
delete_sqs_queue image-result
delete_sqs_queue vlb-preisreferenz-splitting-result
delete_sqs_queue parsing-result
delete_sqs_queue artikel-transformations-service-artikel-ausgang
delete_sqs_queue daten-lieferanten-service-daten-eingang
delete_sqs_queue daten-datenlieferanten-notification
delete_sqs_queue textannotation-result
delete_sqs_queue bilderlink
delete_sqs_queue produktmeldung-parsing
delete_sqs_queue image-delete-notification
delete_sqs_queue onix3-datenlieferant-updates
delete_sqs_queue protokollierung-datenlieferant-updates
delete_sqs_queue katalogdaten
delete_sqs_queue onix3-tmp-parsing-input-event
delete_sqs_queue onix3-tmp-anreicherungs-input-event
delete_sqs_queue inventory-feed-parsing-result

#
# Delete lambda function
#
delete_lambda_function ftp-file-copy
delete_lambda_function ftp-file-distribution
create_lambda_function image-transformation

#
# Delete SNS topic
#
delete_sns_topic protokollierung-topic
delete_sns_topic datenlieferant-updates
