#!/bin/bash

#
# Create S3 buckets
#
awsmock s3 mb s3://file-delivery1
awsmock s3 mb s3://file-delivery2
awsmock s3 mb s3://file-delivery3

#
# Create SQS Queues
#
awsmock sqs create-queue --queue-name=file-delivery-queue
awsmock sqs create-queue --queue-name=file-delivery-dlqueue
awsmock sqs create-queue --queue-name=file-logging-queue

#
# Setup SQS queue attributes
#
awsmock sqs set-queue-attributes --queue-url http://localhost:4567/000000000000/file-delivery1-queue --attributes file://./sqs/file-delivery1-queue.json
awsmock sqs set-queue-attributes --queue-url http://localhost:4567/000000000000/file-delivery2-queue --attributes file://./sqs/file-delivery3-queue.json
awsmock sqs set-queue-attributes --queue-url http://localhost:4567/000000000000/file-delivery3-queue --attributes file://./sqs/file-delivery3-queue.json

#
# DLQ definition
#
awsmock sqs set-queue-attributes --queue-url http://localhost:4567/000000000000/file-delivery-queue --attributes file://./sqs/file-delivery1-queue-attributes.json

#
# Setup S3 bucket notification events
#
awsmock s3api put-bucket-notification-configuration --bucket file-delivery1 --notification-configuration file://./s3/file-delivery1-hook.json
awsmock s3api put-bucket-notification-configuration --bucket file-delivery2 --notification-configuration file://./s3/file-delivery2-hook.json
awsmock s3api put-bucket-notification-configuration --bucket file-delivery3 --notification-configuration file://./s3/file-delivery3-hook.json

#
# Put some objects
#
awsmock s3 cp ./images/0036089631545_ANNO_OBILD.jpg s3://file-delivery1
awsmock s3 cp ./images/9781406379990_ANNO_OBILD.jpg s3://file-delivery1
awsmock s3 cp ./images/0036089631545_ANNO_OBILD.jpg s3://file-delivery2/folder1/0036089631545_ANNO_OBILD.jpg
awsmock s3 cp ./images/9781406379990_ANNO_OBILD.jpg s3://file-delivery2/folder1/9781406379990_ANNO_OBILD.jpg
awsmock s3 cp ./images/0036089631545_ANNO_OBILD.jpg s3://file-delivery3/folder1/folder2/0036089631545_ANNO_OBILD.jpg
awsmock s3 cp ./images/9781406379990_ANNO_OBILD.jpg s3://file-delivery3/folder1/folder2/9781406379990_ANNO_OBILD.jpg

#
# Create lambda function
#
awsmock lambda create-function \
--function-name ftp-file-copy \
--runtime java17 \
--environment file://env.json \
--handler org.springframework.cloud.function.adapter.aws.FunctionInvoker \
--region eu-central-1 \
--zip-file fileb:///tmp/awsmock/data/lambda/file-copy-service-1.14.0-SNAPSHOT-aws.jar \
--role arn:aws:iam::000000000000:role/ignoreme

#
# Create SNS topic
#
awsmock sns create-topic --name file-logging-topic

#
# SNS -> SQS subscription
#
awsmock sns subscribe \
--topic-arn arn:aws:sns:eu-central-1:000000000000:file-logging-topic \
--protocol sqs \
--notification-endpoint arn:aws:sqs:eu-central-1:000000000000:file-logging-queue